CREATE SEQUENCE IF NOT EXISTS component_file_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS component_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS tokens_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS user_component_vote_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE category
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    CONSTRAINT pk_category PRIMARY KEY (id)
);

CREATE TABLE component
(
    id          BIGINT NOT NULL,
    user_id     BIGINT NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    image_url   VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    file_id     BIGINT,
    CONSTRAINT pk_component PRIMARY KEY (id)
);

CREATE TABLE component_category
(
    category_id  BIGINT NOT NULL,
    component_id BIGINT NOT NULL,
    CONSTRAINT pk_component_category PRIMARY KEY (category_id, component_id)
);

CREATE TABLE component_file
(
    id           BIGINT NOT NULL,
    filename     VARCHAR(255),
    size         BIGINT NOT NULL,
    file_content OID,
    CONSTRAINT pk_componentfile PRIMARY KEY (id)
);

CREATE TABLE roles
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                             NOT NULL,
    description VARCHAR(255),
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE tokens
(
    id      BIGINT  NOT NULL,
    token   VARCHAR(500),
    type    VARCHAR(255),
    revoked BOOLEAN NOT NULL,
    expired BOOLEAN NOT NULL,
    user_id BIGINT,
    CONSTRAINT pk_tokens PRIMARY KEY (id)
);

CREATE TABLE user_component_vote
(
    id           BIGINT       NOT NULL,
    user_id      BIGINT       NOT NULL,
    component_id BIGINT       NOT NULL,
    vote_type    VARCHAR(255) NOT NULL,
    CONSTRAINT pk_user_component_vote PRIMARY KEY (id)
);

CREATE TABLE users
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username                VARCHAR(255)                            NOT NULL,
    email                   VARCHAR(255)                            NOT NULL,
    password                VARCHAR(255)                            NOT NULL,
    profile_picture_url     VARCHAR(255),
    verification_code       VARCHAR(50),
    verification_expiration TIMESTAMP WITHOUT TIME ZONE,
    account_locked          BOOLEAN                                 NOT NULL,
    enabled                 BOOLEAN                                 NOT NULL,
    account_expired         BOOLEAN                                 NOT NULL,
    credentials_expired     BOOLEAN                                 NOT NULL,
    join_date               TIMESTAMP WITHOUT TIME ZONE,
    role_id                 INTEGER                                 NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE component
    ADD CONSTRAINT uc_349a0ca5aa51895c907cf5dd4 UNIQUE (user_id, name);

ALTER TABLE user_component_vote
    ADD CONSTRAINT uc_8acff1840d2eaf9af9020a2ff UNIQUE (user_id, component_id);

ALTER TABLE category
    ADD CONSTRAINT uc_category_name UNIQUE (name);

ALTER TABLE component
    ADD CONSTRAINT uc_component_file UNIQUE (file_id);

ALTER TABLE roles
    ADD CONSTRAINT uc_fd322f7161fc2fbfed95c3840 UNIQUE (name);

ALTER TABLE tokens
    ADD CONSTRAINT uc_tokens_token UNIQUE (token);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE users
    ADD CONSTRAINT uc_users_verification_code UNIQUE (verification_code);

ALTER TABLE component
    ADD CONSTRAINT FK_COMPONENT_ON_FILE FOREIGN KEY (file_id) REFERENCES component_file (id);

ALTER TABLE component
    ADD CONSTRAINT FK_COMPONENT_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE tokens
    ADD CONSTRAINT FK_TOKENS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_ROLE FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE user_component_vote
    ADD CONSTRAINT FK_USER_COMPONENT_VOTE_ON_COMPONENT FOREIGN KEY (component_id) REFERENCES component (id);

ALTER TABLE user_component_vote
    ADD CONSTRAINT FK_USER_COMPONENT_VOTE_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE component_category
    ADD CONSTRAINT fk_comcat_on_category FOREIGN KEY (category_id) REFERENCES category (id);

ALTER TABLE component_category
    ADD CONSTRAINT fk_comcat_on_component FOREIGN KEY (component_id) REFERENCES component (id);