services:
  postgres:
    container_name: postgres-sql-comphub
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: compDB
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - spring-demo
    restart: unless-stopped
  mail-dev: # This image is for development
    container_name: mail-dev-comphub
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
#  keycloak:
#    container_name: keycloack-comphub
#    image: quay.io/keycloak/keycloak:26.0.7
#    ports:
#      - "9090:8080"
#    environment:
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: admin
#    networks:
#      - spring-demo
#    command:
#      - "start-dev"
  spring-boot-app: # For local development
    container_name: spring-boot-app
    image: comp-hub-app
    environment:
      SPRING_PROFILES_ACTIVE: default
      DATABASE_URL: jdbc:postgresql://postgres:5432/compDB
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - spring-demo


networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local